<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__InvoiceFormmrn</name>
   <tag></tag>
   <elementGuidId>2755df9b-af1f-4cb7-aca7-a27378ba6ef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InvoiceForm:mrn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>628c913f-8083-45cd-8b2d-cf7766a0ba50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>005436ab-557a-4e8b-ba5e-c9c3f97a980c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>502001f4-2722-4e55-8921-91be083c4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce8f2f3f-2a8a-4f40-a4d2-bc1dc5c5e9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>APM-IP-0000130</value>
      <webElementGuid>a81a4fe3-f4aa-47b4-b815-cbe021d6a7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>   -   The concatenation of all external provider invoice reference numbers sorted alphabetically and separated by '@'.                                  -   Rationale: In some insurer-provider relationships, the provider does not record the insurer's Claims number (ClaimIDPayer) and the insurer does not record the provider's Claim number either (ClaimID).                                  -   Financial transactions are instead communicated using the provider's invoice number.                                  -   The only way to reconcile payments at the level of a Claim is to define a reference number ClaimIDInvoice by concatenating each of the provider external reference numbers on the invoices relating to the Claim.                                  -   This creates a unique key for the Claim, which can be created independently by the provider as well as the insurer.                                  -   It can thus be used to uniquely identify a Claim.</value>
      <webElementGuid>6d3f7f7d-e494-4f99-b48d-e90650473635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;InvoiceForm:mrn&quot;,e:&quot;blur&quot;,p:&quot;InvoiceForm:mrn&quot;});</value>
      <webElementGuid>687d44c4-1c21-404a-ac0e-b1dfadc47255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>178a30fa-9c54-431f-b2cc-1cf8acbed21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b367c89c-f9fb-4720-af12-502577f20a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>959f457a-0c30-471b-a94c-5826ebc3013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29922dfe-8a6c-4466-ad2d-c15f045f1c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:mrn&quot;)</value>
      <webElementGuid>a17f63a7-bb37-4020-b65a-81753deb8f59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InvoiceForm:mrn']</value>
      <webElementGuid>4f5b1084-7fd3-43e3-94e6-e54a5d598e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='InvoiceForm:encounterGroup']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>51fb7b3a-b9cd-42d4-9f14-df348517c756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c62479ee-65fe-4b21-9afc-c3a75397412c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InvoiceForm:mrn' and @name = 'InvoiceForm:mrn' and @type = 'text' and @title = concat(&quot;   -   The concatenation of all external provider invoice reference numbers sorted alphabetically and separated by &quot; , &quot;'&quot; , &quot;@&quot; , &quot;'&quot; , &quot;.                                  -   Rationale: In some insurer-provider relationships, the provider does not record the insurer&quot; , &quot;'&quot; , &quot;s Claims number (ClaimIDPayer) and the insurer does not record the provider&quot; , &quot;'&quot; , &quot;s Claim number either (ClaimID).                                  -   Financial transactions are instead communicated using the provider&quot; , &quot;'&quot; , &quot;s invoice number.                                  -   The only way to reconcile payments at the level of a Claim is to define a reference number ClaimIDInvoice by concatenating each of the provider external reference numbers on the invoices relating to the Claim.                                  -   This creates a unique key for the Claim, which can be created independently by the provider as well as the insurer.                                  -   It can thus be used to uniquely identify a Claim.&quot;)]</value>
      <webElementGuid>9b95c282-24d9-4652-b4ae-2e395e07f0b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
