<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hospital Inpatient - patient occupies in_dee41f</name>
   <tag></tag>
   <elementGuidId>0adf6f31-d1dc-4dd0-b40d-02bbd3569032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='InvoiceForm:icd_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7317d341-1d69-4969-b560-c8306c07df94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>b4024061-8b64-4a96-a44e-7b5d700e0b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>ee270db7-8b55-4182-9096-d4fa353b2116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>10dafd8f-fc6b-4d6b-9a64-2fba44108241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cd7e7f81-ea45-46a1-9748-35ce07c1ccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:icd_4</value>
      <webElementGuid>2d64ede3-5600-412b-b49f-e0646129c70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>16a549ae-4d6c-4dcc-b336-265e52d4a60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:icd_4&quot;)</value>
      <webElementGuid>04b1eb1c-483a-470f-837a-62d5dc430aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='InvoiceForm:icd_4']</value>
      <webElementGuid>4c0398f4-7e87-4c06-b69f-c805a0eebff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='InvoiceForm:icd_items']/li[5]</value>
      <webElementGuid>71d2f2f1-68f8-4281-a2d2-faa2ac9b19c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Health Care – patient is seen in the home'])[4]/following::li[1]</value>
      <webElementGuid>f97072cd-4fef-4328-bbc3-4423cbe9ea01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency - patient is seen in Emergency Department and is not admitted to Inpatient Bed'])[4]/following::li[2]</value>
      <webElementGuid>bf15564d-72d1-4c5e-b19b-7ee2b575f739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Admission'])[4]/preceding::li[2]</value>
      <webElementGuid>e86bd953-a716-4948-8ef0-c31b7ed3f689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[82]/div/ul/li[5]</value>
      <webElementGuid>0349ba67-c68b-4bf7-bc7b-df4c27923fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'InvoiceForm:icd_4' and (text() = 'Hospital Inpatient - patient occupies inpatient bed and stays overnight' or . = 'Hospital Inpatient - patient occupies inpatient bed and stays overnight')]</value>
      <webElementGuid>840c71d2-ee23-44fc-8587-f22ef32bffe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
