<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Diagnosis  Consultation Codes</name>
   <tag></tag>
   <elementGuidId>d38866f5-cc3f-4398-afb2-eac0c66e6a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-tabs-header.ui-state-default.ui-corner-top.ui-state-hover > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabView']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9da98d0a-b6cd-44a6-9d7d-cb10ed8e090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#j_idt953</value>
      <webElementGuid>bb92797c-d1e4-47bd-bf5c-2a415e7bb1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ec2e4594-b8ce-48ff-95a3-9db8c9e0d2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diagnosis &amp; Consultation Codes</value>
      <webElementGuid>4a84f6de-d0f1-402b-9778-bdd092bcf63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabView&quot;)/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-tabs-header ui-state-default ui-corner-top ui-state-hover&quot;]/a[1]</value>
      <webElementGuid>7f1303cb-6eff-47f2-bfdb-1b3998e55f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabView']/ul/li[2]/a</value>
      <webElementGuid>73ec222e-64d4-4b16-98e0-03b7cc5a37e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Diagnosis &amp; Consultation Codes')]</value>
      <webElementGuid>2151c947-d524-4a28-92cd-802963b492c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient &amp; Encounter Info'])[1]/following::a[1]</value>
      <webElementGuid>bd4fc011-900f-4adb-aa33-85d46cd7a907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Details'])[1]/following::a[3]</value>
      <webElementGuid>6ac6eb6e-20c9-4880-a25a-72782f7c121e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Rules'])[1]/preceding::a[1]</value>
      <webElementGuid>90d2ab19-0db2-4187-bb41-07df18e9799c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Notes / Attachments'])[1]/preceding::a[2]</value>
      <webElementGuid>5b40556c-61d1-4ace-a61d-e205daded4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Diagnosis &amp; Consultation Codes']/parent::*</value>
      <webElementGuid>ddcd1fcb-4bf7-4c67-9ead-ce8c24e987b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#j_idt953')]</value>
      <webElementGuid>23e0041c-f6a4-4c14-9ffb-39b169580c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>5a6e6b8b-ea30-452e-b6bd-71707cf7b206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#j_idt953' and (text() = 'Diagnosis &amp; Consultation Codes' or . = 'Diagnosis &amp; Consultation Codes')]</value>
      <webElementGuid>20aebadf-b941-4a01-88fa-e949ac367724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
