<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MRNNational IDNameMiddlenameSurnameArab_04ed56</name>
   <tag></tag>
   <elementGuidId>724d6c86-a4f7-4daf-9e83-bea40493198a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedPatientCreateForm:display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c57a98a-05cb-4f36-997c-7ea583b83cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientCreateForm:display</value>
      <webElementGuid>429fde5f-372d-48ba-9209-d9839e1a762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>


MRN*National ID







Name*Middlename*Surname*Arabic First NameArabic Middle NameArabic Sure NameGender*...FemaleMaleMalePassport IDDOB / Age :*NationalityAFGHANISTANALAND ISLANDSALBANIAALGERIAAMERICAN SAMOAANDORRAANGOLAANGUILLAANTARCTICAANTIGUA AND BARBUDAARGENTINAARMENIAARUBAAUSTRALIAAUSTRIAAZERBAIJANBAHAMASBAHRAINBANGLADESHBARBADOSBELARUSBELGIUMBELIZEBENINBERMUDABHUTANBOLIVIA, PLURINATIONAL STATE OFBONAIRE, SINT EUSTATIUS AND SABABOSNIA AND HERZEGOVINABOTSWANABOUVET ISLANDBRAZILBRITISH INDIAN OCEAN TERRITORYBRUNEI DARUSSALAMBULGARIABURKINA FASOBURUNDICAMBODIACAMEROONCANADACAPE VERDECAYMAN ISLANDSCENTRAL AFRICAN REPUBLICCHADCHILECHINACHRISTMAS ISLANDCOCOS (KEELING) ISLANDSCOLOMBIACOMOROSCONGOCONGO, THE DEMOCRATIC REPUBLIC OF THECOOK ISLANDSCOSTA RICACOTE D'IVOIRECROATIACUBACURACAOCYPRUSCZECH REPUBLICDENMARKDJIBOUTIDOMINICADOMINICAN REPUBLICECUADOREGYPTEL SALVADOREQUATORIAL GUINEAERITREAESTONIAETHIOPIAFALKLAND ISLANDS (MALVINAS)FAROE ISLANDSFIJIFINLANDFRANCEFRENCH GUIANAFRENCH POLYNESIAFRENCH SOUTHERN TERRITORIESGABONGAMBIAGEORGIAGERMANYGHANAGIBRALTARGREECEGREENLANDGRENADAGUADELOUPEGUAMGUATEMALAGUERNSEYGUINEAGUINEA-BISSAUGUYANAHAITIHEARD ISLAND AND MCDONALD ISLANDSHOLY SEE (VATICAN CITY STATE)HONDURASHONG KONGHUNGARYICELANDINDIAINDONESIAIRAN (ISLAMIC REPUBLIC OF)IRAQIRELANDISLE OF MANISRAELITALYJAMAICAJAPANJERSEYJORDANKAZAKHSTANKENYAKIRIBATIKOREA, DEMOCRATIC PEOPLE'S REPUBLIC OFKOREA, REPUBLIC OFKUWAITKYRGYZSTANLAO PEOPLE'S DEMOCRATIC REPUBLICLATVIALEBANONLESOTHOLIBERIALIBYALIECHTENSTEINLITHUANIALUXEMBOURGMACAOMACEDONIA, THE FORMER YUGOSLAV REPUBLIC OFMADAGASCARMALAWIMALAYSIAMALDIVESMALIMALTAMARSHALL ISLANDSMARTINIQUEMAURITANIAMAURITIUSMAYOTTEMEXICOMICRONESIA, FEDERATED STATES OFMOLDOVA, REPUBLIC OFMONACOMONGOLIAMONTENEGROMONTSERRATMOROCCOMOZAMBIQUEMYANMARNAMIBIANAURUNEPALNETHERLANDSNEW CALEDONIANEW ZEALANDNICARAGUANIGERNIGERIANIUENORFOLK ISLANDNORTHERN MARIANA ISLANDSNORWAYNOT APPLICABLEOMANPAKISTANPALAUPALESTINIAN TERRITORY, OCCUPIEDPANAMAPAPUA NEW GUINEAPARAGUAYPERUPHILIPPINESPITCAIRNPOLANDPORTUGALPUERTO RICOQATARREUNIONROMANIARUSSIAN FEDERATIONRWANDASAINT BARTHELEMYSAINT HELENA, ASCENSION AND TRISTAN DA CUNHASSAINT KITTS AND NEVISSAINT LUCIASAINT MARTIN (FRENCH PART)SAINT PIERRE AND MIQUELONSAINT VINCENT AND THE GRENADINESSAMOASAN MARINOSAO TOME AND PRINCIPESAUDI ARABIASENEGALSERBIASEYCHELLESSIERRA LEONESINGAPORESINT MAARTEN (DUTCH PART)SLOVAKIASLOVENIASOLOMON ISLANDSSOMALIASOUTH AFRICASOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDSSOUTH SUDANSPAINSRI LANKASUDANSURINAMESVALBARD AND JAN MAYENSWAZILANDSWEDENSWITZERLANDSYRIAN ARAB REPUBLICTAIWAN, PROVINCE OF CHINATAJIKISTANTANZANIA, UNITED REPUBLIC OFTHAILANDTIMOR-LESTETOGOTOKELAUTONGATRINIDAD AND TOBAGOTUNISIATURKEYTURKMENISTANTURKS AND CAICOS ISLANDSTUVALUUGANDAUKRAINEUNITED ARAB EMIRATESUNITED KINGDOMUNITED STATESUNITED STATES MINOR OUTLYING ISLANDSURUGUAYUZBEKISTANVANUATUVATICAN CITY STATE (HOLY SEE)VENEZUELA, BOLIVARIAN REPUBLIC OFVIET NAMVIRGIN ISLANDS (BRITISH)VIRGIN ISLANDS (U.S.)WALLIS AND FUTUNAWESTERN SAHARAYEMENYUGOSLAVIAZAMBIAZIMBABWEAFGHANISTANMarital StatusSelect One...DivorcedMarriedSeparatedSingleUnknownWidowedSelect One...HomeOfficeFaxMobilePersonEmailAdd Insurance Card



Member IDPayer IDPolicy/ClassStart DateEnd DateEditDeleteNo record found.</value>
      <webElementGuid>3513eafe-4015-4c8c-a4c8-285acecfa63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientCreateForm:display&quot;)</value>
      <webElementGuid>3269a77e-9f5d-430b-9999-93c660b88f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AccumedPatientCreateForm:display']</value>
      <webElementGuid>3a7e667d-e264-4a86-ab62-cda631c91f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AccumedPatientCreateForm']/div</value>
      <webElementGuid>a277b70b-dd5a-4284-841d-61da0f160097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Patient'])[1]/following::div[2]</value>
      <webElementGuid>3463f773-d62e-4fe7-8457-09a3cdf0b13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[2]/following::div[4]</value>
      <webElementGuid>3fb21d6f-ea49-4769-af6b-816426d0b5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/form/div</value>
      <webElementGuid>9f8acaed-2eb7-477e-a9f8-49d61d8e85f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'AccumedPatientCreateForm:display' and (text() = concat(&quot;


MRN*National ID







Name*Middlename*Surname*Arabic First NameArabic Middle NameArabic Sure NameGender*...FemaleMaleMalePassport IDDOB / Age :*NationalityAFGHANISTANALAND ISLANDSALBANIAALGERIAAMERICAN SAMOAANDORRAANGOLAANGUILLAANTARCTICAANTIGUA AND BARBUDAARGENTINAARMENIAARUBAAUSTRALIAAUSTRIAAZERBAIJANBAHAMASBAHRAINBANGLADESHBARBADOSBELARUSBELGIUMBELIZEBENINBERMUDABHUTANBOLIVIA, PLURINATIONAL STATE OFBONAIRE, SINT EUSTATIUS AND SABABOSNIA AND HERZEGOVINABOTSWANABOUVET ISLANDBRAZILBRITISH INDIAN OCEAN TERRITORYBRUNEI DARUSSALAMBULGARIABURKINA FASOBURUNDICAMBODIACAMEROONCANADACAPE VERDECAYMAN ISLANDSCENTRAL AFRICAN REPUBLICCHADCHILECHINACHRISTMAS ISLANDCOCOS (KEELING) ISLANDSCOLOMBIACOMOROSCONGOCONGO, THE DEMOCRATIC REPUBLIC OF THECOOK ISLANDSCOSTA RICACOTE D&quot; , &quot;'&quot; , &quot;IVOIRECROATIACUBACURACAOCYPRUSCZECH REPUBLICDENMARKDJIBOUTIDOMINICADOMINICAN REPUBLICECUADOREGYPTEL SALVADOREQUATORIAL GUINEAERITREAESTONIAETHIOPIAFALKLAND ISLANDS (MALVINAS)FAROE ISLANDSFIJIFINLANDFRANCEFRENCH GUIANAFRENCH POLYNESIAFRENCH SOUTHERN TERRITORIESGABONGAMBIAGEORGIAGERMANYGHANAGIBRALTARGREECEGREENLANDGRENADAGUADELOUPEGUAMGUATEMALAGUERNSEYGUINEAGUINEA-BISSAUGUYANAHAITIHEARD ISLAND AND MCDONALD ISLANDSHOLY SEE (VATICAN CITY STATE)HONDURASHONG KONGHUNGARYICELANDINDIAINDONESIAIRAN (ISLAMIC REPUBLIC OF)IRAQIRELANDISLE OF MANISRAELITALYJAMAICAJAPANJERSEYJORDANKAZAKHSTANKENYAKIRIBATIKOREA, DEMOCRATIC PEOPLE&quot; , &quot;'&quot; , &quot;S REPUBLIC OFKOREA, REPUBLIC OFKUWAITKYRGYZSTANLAO PEOPLE&quot; , &quot;'&quot; , &quot;S DEMOCRATIC REPUBLICLATVIALEBANONLESOTHOLIBERIALIBYALIECHTENSTEINLITHUANIALUXEMBOURGMACAOMACEDONIA, THE FORMER YUGOSLAV REPUBLIC OFMADAGASCARMALAWIMALAYSIAMALDIVESMALIMALTAMARSHALL ISLANDSMARTINIQUEMAURITANIAMAURITIUSMAYOTTEMEXICOMICRONESIA, FEDERATED STATES OFMOLDOVA, REPUBLIC OFMONACOMONGOLIAMONTENEGROMONTSERRATMOROCCOMOZAMBIQUEMYANMARNAMIBIANAURUNEPALNETHERLANDSNEW CALEDONIANEW ZEALANDNICARAGUANIGERNIGERIANIUENORFOLK ISLANDNORTHERN MARIANA ISLANDSNORWAYNOT APPLICABLEOMANPAKISTANPALAUPALESTINIAN TERRITORY, OCCUPIEDPANAMAPAPUA NEW GUINEAPARAGUAYPERUPHILIPPINESPITCAIRNPOLANDPORTUGALPUERTO RICOQATARREUNIONROMANIARUSSIAN FEDERATIONRWANDASAINT BARTHELEMYSAINT HELENA, ASCENSION AND TRISTAN DA CUNHASSAINT KITTS AND NEVISSAINT LUCIASAINT MARTIN (FRENCH PART)SAINT PIERRE AND MIQUELONSAINT VINCENT AND THE GRENADINESSAMOASAN MARINOSAO TOME AND PRINCIPESAUDI ARABIASENEGALSERBIASEYCHELLESSIERRA LEONESINGAPORESINT MAARTEN (DUTCH PART)SLOVAKIASLOVENIASOLOMON ISLANDSSOMALIASOUTH AFRICASOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDSSOUTH SUDANSPAINSRI LANKASUDANSURINAMESVALBARD AND JAN MAYENSWAZILANDSWEDENSWITZERLANDSYRIAN ARAB REPUBLICTAIWAN, PROVINCE OF CHINATAJIKISTANTANZANIA, UNITED REPUBLIC OFTHAILANDTIMOR-LESTETOGOTOKELAUTONGATRINIDAD AND TOBAGOTUNISIATURKEYTURKMENISTANTURKS AND CAICOS ISLANDSTUVALUUGANDAUKRAINEUNITED ARAB EMIRATESUNITED KINGDOMUNITED STATESUNITED STATES MINOR OUTLYING ISLANDSURUGUAYUZBEKISTANVANUATUVATICAN CITY STATE (HOLY SEE)VENEZUELA, BOLIVARIAN REPUBLIC OFVIET NAMVIRGIN ISLANDS (BRITISH)VIRGIN ISLANDS (U.S.)WALLIS AND FUTUNAWESTERN SAHARAYEMENYUGOSLAVIAZAMBIAZIMBABWEAFGHANISTANMarital StatusSelect One...DivorcedMarriedSeparatedSingleUnknownWidowedSelect One...HomeOfficeFaxMobilePersonEmailAdd Insurance Card



Member IDPayer IDPolicy/ClassStart DateEnd DateEditDeleteNo record found.&quot;) or . = concat(&quot;


MRN*National ID







Name*Middlename*Surname*Arabic First NameArabic Middle NameArabic Sure NameGender*...FemaleMaleMalePassport IDDOB / Age :*NationalityAFGHANISTANALAND ISLANDSALBANIAALGERIAAMERICAN SAMOAANDORRAANGOLAANGUILLAANTARCTICAANTIGUA AND BARBUDAARGENTINAARMENIAARUBAAUSTRALIAAUSTRIAAZERBAIJANBAHAMASBAHRAINBANGLADESHBARBADOSBELARUSBELGIUMBELIZEBENINBERMUDABHUTANBOLIVIA, PLURINATIONAL STATE OFBONAIRE, SINT EUSTATIUS AND SABABOSNIA AND HERZEGOVINABOTSWANABOUVET ISLANDBRAZILBRITISH INDIAN OCEAN TERRITORYBRUNEI DARUSSALAMBULGARIABURKINA FASOBURUNDICAMBODIACAMEROONCANADACAPE VERDECAYMAN ISLANDSCENTRAL AFRICAN REPUBLICCHADCHILECHINACHRISTMAS ISLANDCOCOS (KEELING) ISLANDSCOLOMBIACOMOROSCONGOCONGO, THE DEMOCRATIC REPUBLIC OF THECOOK ISLANDSCOSTA RICACOTE D&quot; , &quot;'&quot; , &quot;IVOIRECROATIACUBACURACAOCYPRUSCZECH REPUBLICDENMARKDJIBOUTIDOMINICADOMINICAN REPUBLICECUADOREGYPTEL SALVADOREQUATORIAL GUINEAERITREAESTONIAETHIOPIAFALKLAND ISLANDS (MALVINAS)FAROE ISLANDSFIJIFINLANDFRANCEFRENCH GUIANAFRENCH POLYNESIAFRENCH SOUTHERN TERRITORIESGABONGAMBIAGEORGIAGERMANYGHANAGIBRALTARGREECEGREENLANDGRENADAGUADELOUPEGUAMGUATEMALAGUERNSEYGUINEAGUINEA-BISSAUGUYANAHAITIHEARD ISLAND AND MCDONALD ISLANDSHOLY SEE (VATICAN CITY STATE)HONDURASHONG KONGHUNGARYICELANDINDIAINDONESIAIRAN (ISLAMIC REPUBLIC OF)IRAQIRELANDISLE OF MANISRAELITALYJAMAICAJAPANJERSEYJORDANKAZAKHSTANKENYAKIRIBATIKOREA, DEMOCRATIC PEOPLE&quot; , &quot;'&quot; , &quot;S REPUBLIC OFKOREA, REPUBLIC OFKUWAITKYRGYZSTANLAO PEOPLE&quot; , &quot;'&quot; , &quot;S DEMOCRATIC REPUBLICLATVIALEBANONLESOTHOLIBERIALIBYALIECHTENSTEINLITHUANIALUXEMBOURGMACAOMACEDONIA, THE FORMER YUGOSLAV REPUBLIC OFMADAGASCARMALAWIMALAYSIAMALDIVESMALIMALTAMARSHALL ISLANDSMARTINIQUEMAURITANIAMAURITIUSMAYOTTEMEXICOMICRONESIA, FEDERATED STATES OFMOLDOVA, REPUBLIC OFMONACOMONGOLIAMONTENEGROMONTSERRATMOROCCOMOZAMBIQUEMYANMARNAMIBIANAURUNEPALNETHERLANDSNEW CALEDONIANEW ZEALANDNICARAGUANIGERNIGERIANIUENORFOLK ISLANDNORTHERN MARIANA ISLANDSNORWAYNOT APPLICABLEOMANPAKISTANPALAUPALESTINIAN TERRITORY, OCCUPIEDPANAMAPAPUA NEW GUINEAPARAGUAYPERUPHILIPPINESPITCAIRNPOLANDPORTUGALPUERTO RICOQATARREUNIONROMANIARUSSIAN FEDERATIONRWANDASAINT BARTHELEMYSAINT HELENA, ASCENSION AND TRISTAN DA CUNHASSAINT KITTS AND NEVISSAINT LUCIASAINT MARTIN (FRENCH PART)SAINT PIERRE AND MIQUELONSAINT VINCENT AND THE GRENADINESSAMOASAN MARINOSAO TOME AND PRINCIPESAUDI ARABIASENEGALSERBIASEYCHELLESSIERRA LEONESINGAPORESINT MAARTEN (DUTCH PART)SLOVAKIASLOVENIASOLOMON ISLANDSSOMALIASOUTH AFRICASOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDSSOUTH SUDANSPAINSRI LANKASUDANSURINAMESVALBARD AND JAN MAYENSWAZILANDSWEDENSWITZERLANDSYRIAN ARAB REPUBLICTAIWAN, PROVINCE OF CHINATAJIKISTANTANZANIA, UNITED REPUBLIC OFTHAILANDTIMOR-LESTETOGOTOKELAUTONGATRINIDAD AND TOBAGOTUNISIATURKEYTURKMENISTANTURKS AND CAICOS ISLANDSTUVALUUGANDAUKRAINEUNITED ARAB EMIRATESUNITED KINGDOMUNITED STATESUNITED STATES MINOR OUTLYING ISLANDSURUGUAYUZBEKISTANVANUATUVATICAN CITY STATE (HOLY SEE)VENEZUELA, BOLIVARIAN REPUBLIC OFVIET NAMVIRGIN ISLANDS (BRITISH)VIRGIN ISLANDS (U.S.)WALLIS AND FUTUNAWESTERN SAHARAYEMENYUGOSLAVIAZAMBIAZIMBABWEAFGHANISTANMarital StatusSelect One...DivorcedMarriedSeparatedSingleUnknownWidowedSelect One...HomeOfficeFaxMobilePersonEmailAdd Insurance Card



Member IDPayer IDPolicy/ClassStart DateEnd DateEditDeleteNo record found.&quot;))]</value>
      <webElementGuid>55411f64-dc6b-4117-bb2f-c3dc562370d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
