<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_timeUnit_AccumedHaadActivityListForma_6ca34a</name>
   <tag></tag>
   <elementGuidId>a49c302c-936c-4614-bb93-28fc7b671f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedHaadActivityListForm:activityCode_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d2857fb-f8a2-4fbc-98c2-b9918fe4e791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:activityCode_input</value>
      <webElementGuid>6062f300-72ca-44a6-98ec-020a6b9b0586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:activityCode_input</value>
      <webElementGuid>bb827cd8-fe35-48ea-9b3a-ba82d2e40e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b838a8dd-8d56-4596-8e4b-f28e419c2e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>ad262aae-6958-476b-92c6-99b688cf18ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3daf593a-9408-48d6-b7b9-e35808acf94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>AccumedHaadActivityListForm:j_idt1937</value>
      <webElementGuid>16f5679c-481d-4e9a-bf2c-61fa103da94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3b4ecde7-5985-4f92-b903-b9a4c788699a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;AccumedHaadActivityListForm:activityCode&quot;,e:&quot;keypress&quot;,p:&quot;AccumedHaadActivityListForm:activityCode&quot;,u:&quot;AccumedHaadActivityListForm:activityCode AccumedHaadActivityListForm:activityList AccumedHaadActivityListForm:totalPrice AccumedHaadActivityListForm:startDate AccumedHaadActivityListForm:activityClinician AccumedHaadActivityListForm:contractSuspendErrorsRefresh growl AccumedHaadActivityListForm:activityDrugType AccumedHaadActivityListForm:activityDrugTypeLabel&quot;,onst:function(cfg){if(event.keyCode!=9)return false;;}});</value>
      <webElementGuid>f5ea00bb-a887-451c-adb0-f05ea986d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>c6ba6251-1fdb-4aa8-9998-5bdabf8e8d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f052d23a-8e14-474a-8912-8ee60c990be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e90542eb-962b-42ca-bdbb-d58e2cdc97f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d762e7c1-ac62-420c-bff9-43e3d20efcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>4851e23c-6add-472d-9c07-e9e6a4104b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedHaadActivityListForm:activityCode_input&quot;)</value>
      <webElementGuid>fd9ee60b-884b-47e5-9469-0486446ba6cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedHaadActivityListForm:activityCode_input']</value>
      <webElementGuid>adc83aa0-d856-4a06-8ef2-c160529e5ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedHaadActivityListForm:activityCode']/input</value>
      <webElementGuid>ffac7f1b-02d1-4396-9053-1be909e15b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/form[2]/fieldset/div/span/table/tbody/tr[2]/td/span/input</value>
      <webElementGuid>78313d5d-8269-4b3b-b42f-3421c93f32b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedHaadActivityListForm:activityCode_input' and @name = 'AccumedHaadActivityListForm:activityCode_input' and @type = 'text']</value>
      <webElementGuid>e14c4db5-c5e9-46f1-b849-893fdc778756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
