<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__InvoiceFormmrn</name>
   <tag></tag>
   <elementGuidId>dece817c-2c87-4133-b40d-f90e2ca248cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InvoiceForm:mrn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ae65c26-91ed-45f6-995e-6a6747264e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>ab542bfd-a868-4c70-a005-601e08739a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>21859930-8fc6-46b5-8aa6-72fdbb2c19c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c39a7280-0b6e-4370-8312-fe7e5ce0466a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>APM-IP-0000134</value>
      <webElementGuid>aae524ee-e8c0-4c32-b9ba-70968dc92ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>   -   The concatenation of all external provider invoice reference numbers sorted alphabetically and separated by '@'.                                  -   Rationale: In some insurer-provider relationships, the provider does not record the insurer's Claims number (ClaimIDPayer) and the insurer does not record the provider's Claim number either (ClaimID).                                  -   Financial transactions are instead communicated using the provider's invoice number.                                  -   The only way to reconcile payments at the level of a Claim is to define a reference number ClaimIDInvoice by concatenating each of the provider external reference numbers on the invoices relating to the Claim.                                  -   This creates a unique key for the Claim, which can be created independently by the provider as well as the insurer.                                  -   It can thus be used to uniquely identify a Claim.</value>
      <webElementGuid>2d30da8c-7736-447b-a468-84403faaba2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;InvoiceForm:mrn&quot;,e:&quot;blur&quot;,p:&quot;InvoiceForm:mrn&quot;});</value>
      <webElementGuid>31052a6e-2222-4a33-b217-0ec27bc483f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>18028bed-4007-42d4-9fe5-ce8d371a0475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>66e84004-23b7-407c-9319-1cf2d05751b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>977cb359-1103-4c4f-bc37-df29466ee1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6492ac72-6a0d-4166-9732-adcf714181e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:mrn&quot;)</value>
      <webElementGuid>820055a0-a011-407b-91de-6a04ac927079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf06a50e-1fc8-4332-b87d-fff959a396f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>39fc0ebe-a8cc-44fb-916d-2f199f360b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InvoiceForm:mrn</value>
      <webElementGuid>0b24e5db-e23b-46a7-9b25-7b4038bff4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5db4ff67-a3d9-4ef1-a741-362956e78f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>APM-IP-0000133</value>
      <webElementGuid>992b52ed-3752-4618-89c9-f0b0f8ee3e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>   -   The concatenation of all external provider invoice reference numbers sorted alphabetically and separated by '@'.                                  -   Rationale: In some insurer-provider relationships, the provider does not record the insurer's Claims number (ClaimIDPayer) and the insurer does not record the provider's Claim number either (ClaimID).                                  -   Financial transactions are instead communicated using the provider's invoice number.                                  -   The only way to reconcile payments at the level of a Claim is to define a reference number ClaimIDInvoice by concatenating each of the provider external reference numbers on the invoices relating to the Claim.                                  -   This creates a unique key for the Claim, which can be created independently by the provider as well as the insurer.                                  -   It can thus be used to uniquely identify a Claim.</value>
      <webElementGuid>d56f668f-6647-4893-ba90-b4a802b361b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;InvoiceForm:mrn&quot;,e:&quot;blur&quot;,p:&quot;InvoiceForm:mrn&quot;});</value>
      <webElementGuid>b8dbaa11-36dd-478f-ba10-ba478b0a2641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>716a3256-8cd5-4493-acc5-dc193d27d1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>207ca8a1-3ef0-45a3-b73f-60791bb4353e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>437b0f38-3796-40aa-8068-1247ecf31cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad0a5353-7852-4638-9fe4-76b4ccea7e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:mrn&quot;)</value>
      <webElementGuid>6dbd630a-c29c-4992-9699-6119b9e7454c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InvoiceForm:mrn']</value>
      <webElementGuid>208192d8-3b11-46b1-9027-9bc1d63fffe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='InvoiceForm:encounterGroup']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d4f9be96-c7f1-4305-9f7c-d8097f93b50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e3f0b287-146a-479d-a825-4e24d342b378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InvoiceForm:mrn' and @name = 'InvoiceForm:mrn' and @type = 'text' and @title = concat(&quot;   -   The concatenation of all external provider invoice reference numbers sorted alphabetically and separated by &quot; , &quot;'&quot; , &quot;@&quot; , &quot;'&quot; , &quot;.                                  -   Rationale: In some insurer-provider relationships, the provider does not record the insurer&quot; , &quot;'&quot; , &quot;s Claims number (ClaimIDPayer) and the insurer does not record the provider&quot; , &quot;'&quot; , &quot;s Claim number either (ClaimID).                                  -   Financial transactions are instead communicated using the provider&quot; , &quot;'&quot; , &quot;s invoice number.                                  -   The only way to reconcile payments at the level of a Claim is to define a reference number ClaimIDInvoice by concatenating each of the provider external reference numbers on the invoices relating to the Claim.                                  -   This creates a unique key for the Claim, which can be created independently by the provider as well as the insurer.                                  -   It can thus be used to uniquely identify a Claim.&quot;)]</value>
      <webElementGuid>f02d0e2d-2456-4319-8b3a-d55a3e5c5144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
