<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Government</name>
   <tag></tag>
   <elementGuidId>6b4ee999-9c03-48ed-ad34-d18317af16e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8356599d-26d6-41eb-b3fa-324ce51fce58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:policyHolderTypeId_label</value>
      <webElementGuid>39538191-4c65-47ba-8d41-0886a0291459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>89a0e763-f092-457f-a99b-34333fe8e1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Government</value>
      <webElementGuid>1f8e49fb-0008-4804-9c5b-006066de182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:policyHolderTypeId_label&quot;)</value>
      <webElementGuid>e9a95888-e2a4-4aa4-87c5-58a8a9003c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId_label']</value>
      <webElementGuid>e88ef3ad-8792-43b9-bc5e-4859a260ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId']/label</value>
      <webElementGuid>8ccbbda3-9dd0-43c7-93ea-53f8df924073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Holder Type'])[1]/following::label[1]</value>
      <webElementGuid>9c571839-99fa-4fa8-9a79-550a850d6904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[2]/following::label[2]</value>
      <webElementGuid>2f3685a2-b05f-4a2a-9c73-bde9db027c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CompanyName'])[1]/preceding::label[1]</value>
      <webElementGuid>53b874b2-730e-4c04-98b0-aa4d56b64a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Number'])[1]/preceding::label[2]</value>
      <webElementGuid>8f9d8983-2a7a-42df-9877-da744443162c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/div/label</value>
      <webElementGuid>e3777c59-be0f-47ba-b8c3-251a72595f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'AccumedPatientInsuranceCreateForm:policyHolderTypeId_label' and (text() = 'Government' or . = 'Government')]</value>
      <webElementGuid>80818299-9588-40f6-88e8-35dac061f5ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
