<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hospital Inpatient - patient occupies in_dee41f</name>
   <tag></tag>
   <elementGuidId>f91d5fb0-7c04-4c54-a9dc-3e057a934fe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='InvoiceForm:icd_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2cd8f805-4882-43b4-ad25-449e7fd1518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>1b6243a1-1342-450d-9a9d-99bfabf0a6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>543821f6-469a-4385-a323-799b4991d5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9e21f762-8e88-49a4-898b-a81307acccf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>39baeacc-5783-4a68-bf39-e7dcdcac2deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:icd_4</value>
      <webElementGuid>8e96dc02-cf33-43a4-a865-42447ca34fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>f9d68593-dd13-480a-b567-6d3b0502e4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:icd_4&quot;)</value>
      <webElementGuid>c65ffd6b-4ef5-4820-9d76-c310f6a3b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0d5122b1-1af7-431c-8e14-6955f222e6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>e3004896-466b-46d2-800a-d0e73a0be2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>3aeb2331-f185-4345-88ca-d0a98a380033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3f32a18f-50ce-459c-809b-3cb251b3d071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7dd9a45e-851e-48be-9d93-2e1cd25b599d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceForm:icd_4</value>
      <webElementGuid>206bc7ab-5341-43cf-99f5-acb5eab328f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hospital Inpatient - patient occupies inpatient bed and stays overnight</value>
      <webElementGuid>98bf4176-f2b9-40cd-89c2-89acd15aae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceForm:icd_4&quot;)</value>
      <webElementGuid>2e9b2f29-084d-4c2e-9b69-6e21b0a626aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='InvoiceForm:icd_4']</value>
      <webElementGuid>fcc544d8-b685-43d3-b4ea-f238b6cee2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='InvoiceForm:icd_items']/li[5]</value>
      <webElementGuid>f95e5c70-8369-49b8-b6da-dce5738f0ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Health Care – patient is seen in the home'])[4]/following::li[1]</value>
      <webElementGuid>51eecf51-c691-4088-8a56-0e399e5b406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency - patient is seen in Emergency Department and is not admitted to Inpatient Bed'])[4]/following::li[2]</value>
      <webElementGuid>5c1836b4-98a6-4141-a4be-65580e13e219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Admission'])[4]/preceding::li[2]</value>
      <webElementGuid>a906a528-1725-46d8-a097-4b9445a4461d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[82]/div/ul/li[5]</value>
      <webElementGuid>53badaac-7bb3-4122-b916-7102e39decb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'InvoiceForm:icd_4' and (text() = 'Hospital Inpatient - patient occupies inpatient bed and stays overnight' or . = 'Hospital Inpatient - patient occupies inpatient bed and stays overnight')]</value>
      <webElementGuid>392687dc-e13c-48df-b193-ba92d04db5b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
