<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Private companies  1000 employees</name>
   <tag></tag>
   <elementGuidId>bfc5a9fd-ec3f-4086-b184-3213b3162348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9b3ff2f6-1f31-4faf-92f9-1af65198d924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>e7328da3-8d1a-41c4-9147-398c8221eec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Private companies >= 1000 employees</value>
      <webElementGuid>82008fd1-8cfe-409a-b59c-38e718bcc157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5f0fec3a-8ce1-4369-9ad6-73fcabbd04e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b4e1377b-6788-4ad2-91ce-d178601bbe53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:policyHolderTypeId_4</value>
      <webElementGuid>b45104e8-aaa3-4c12-b4fc-dd234354f254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Private companies >= 1000 employees</value>
      <webElementGuid>5deb4315-13d0-47e2-a335-0e03b58adc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:policyHolderTypeId_4&quot;)</value>
      <webElementGuid>7a74c35a-79e5-4cc6-b86c-55602b221f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId_4']</value>
      <webElementGuid>135670bd-bd29-402f-a76f-7e441bcb93b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AccumedPatientInsuranceCreateForm:policyHolderTypeId_items']/li[5]</value>
      <webElementGuid>cf7bf2bf-1330-4990-8f8b-cdede620b2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private companies &lt; 1000 employees'])[2]/following::li[1]</value>
      <webElementGuid>d3b303c2-bee5-4275-9a9d-af37fb61316d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Service'])[10]/following::li[2]</value>
      <webElementGuid>b8752319-5e83-4458-821f-f5a990a27429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Admissions Only'])[2]/preceding::li[1]</value>
      <webElementGuid>8c19b57b-66a9-4b36-9cca-56c5955ba11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP and OP Admissions'])[3]/preceding::li[2]</value>
      <webElementGuid>6afe4a62-2de0-435d-be19-6ba2b7f7fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[96]/div/ul/li[5]</value>
      <webElementGuid>267e7978-5794-478b-bea8-51d5cf1ef878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'AccumedPatientInsuranceCreateForm:policyHolderTypeId_4' and (text() = 'Private companies >= 1000 employees' or . = 'Private companies >= 1000 employees')]</value>
      <webElementGuid>35e56e3f-6347-4a1b-a829-13636f478bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
