<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KSP001Self Pay - Cash_ui-button-icon-l_b3bc42</name>
   <tag></tag>
   <elementGuidId>a6994fba-533c-4922-8b3f-f1ad84bacaf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-icon-left.ui-icon.ui-c.fa.fa-th-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='phWLForm:phWLTbl:0:c1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e72c1cc0-2408-4584-8c14-feefae01be17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c fa fa-th-list</value>
      <webElementGuid>203682fc-bf7e-4fea-a540-dacbd97ff4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phWLForm:phWLTbl:0:c1&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c fa fa-th-list&quot;]</value>
      <webElementGuid>82413121-1f8e-42dd-8447-036fbaef6f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='phWLForm:phWLTbl:0:c1']/span</value>
      <webElementGuid>02855faa-138c-4c5c-a5fc-d4288e19c55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[22]/button/span</value>
      <webElementGuid>27017f8a-310c-4170-8486-a205cae3f79d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
