<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Not Verified Insurances_InsuranceDetails_c7a957</name>
   <tag></tag>
   <elementGuidId>9bd5e382-a860-4aec-83fb-a24474d764b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='InsuranceDetailsForm:j_idt1552:datalist:j_idt1554']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>eac81cd4-ea35-4e5f-b338-255607dc196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InsuranceDetailsForm:j_idt1552:datalist:j_idt1554</value>
      <webElementGuid>b7afd7e0-83d2-427d-858e-441680ab78cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default</value>
      <webElementGuid>112f1054-6cd8-4fef-90bd-730149ef7312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>8c886f3f-6dea-4a69-8718-a403c1b5d76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>9b00a652-1a61-4344-b8e0-145593187fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InsuranceDetailsForm:j_idt1552:datalist:j_idt1554&quot;)</value>
      <webElementGuid>9a017db2-ce8b-4c10-a6b7-2012b4b7216f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='InsuranceDetailsForm:j_idt1552:datalist:j_idt1554']</value>
      <webElementGuid>47ca6eb6-dd7d-4663-af3b-b36a686c1fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='InsuranceDetailsForm:j_idt1552:datalist_head']/tr/th</value>
      <webElementGuid>62c1f851-69ac-463c-bbff-a0b87035ea5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Verified Insurances'])[1]/following::th[1]</value>
      <webElementGuid>4b3a7550-945d-4b07-9f49-392ffb1af433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expired Insurances'])[1]/following::th[1]</value>
      <webElementGuid>ee0c89f5-e3bb-4a36-b4ee-487187132bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[3]/preceding::th[1]</value>
      <webElementGuid>bb8e1b50-64d8-4f2d-abd8-b54449ca9565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='InsuranceLisence'])[1]/preceding::th[2]</value>
      <webElementGuid>45a2cde0-19e7-4202-a18f-b38df89d8965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[47]/div[2]/form/div/div/div/div/div/div/div/table/thead/tr/th</value>
      <webElementGuid>f67e96d4-7677-48e0-abaa-cfca760f84fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'InsuranceDetailsForm:j_idt1552:datalist:j_idt1554']</value>
      <webElementGuid>51d85be0-40f9-4289-8e10-87be34f0c7f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
