<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AccumedPatientInsuranceCreateFormpatientInsuranceId</name>
   <tag></tag>
   <elementGuidId>53d014c9-4c54-467d-8a8f-27c5cf933e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc04a655-4ff5-46bd-9e77-7789f19fff96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>3b76244d-2ec7-44e2-8ac8-3735171f4761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedPatientInsuranceCreateForm:patientInsuranceId</value>
      <webElementGuid>7c3f5171-e4c3-455f-a363-01abb6d09e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e6d2316-6ebd-49a2-8b63-726606ab27c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- The patient's insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.</value>
      <webElementGuid>02898669-ba10-4514-b215-1d9454e112e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>1b0ea441-ef6a-43fd-894b-8797f23f11e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1d252b8a-ae32-449a-8ac3-33478ddcefd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e822d8f-d668-484a-b202-16a9bacca740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd3d0adc-16b3-4c8a-83cb-8af84b929aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedPatientInsuranceCreateForm:patientInsuranceId&quot;)</value>
      <webElementGuid>4f50abaf-1609-44b1-aff8-fe7315f8a5e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedPatientInsuranceCreateForm:patientInsuranceId']</value>
      <webElementGuid>c8a30afc-6795-4968-885c-507ed1cfac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedPatientInsuranceCreateForm:j_idt1254']/tbody/tr/td[2]/input</value>
      <webElementGuid>81608bb4-dff8-4ec5-9103-70304cbbdc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3053b580-2a68-4b4e-9cf7-baad1beaa019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @name = 'AccumedPatientInsuranceCreateForm:patientInsuranceId' and @type = 'text' and @title = concat(&quot;- The patient&quot; , &quot;'&quot; , &quot;s insurance member number, if the patient is claiming insurance.                                              - Otherwise, this field should be left empty.&quot;)]</value>
      <webElementGuid>9528996d-b6ec-4e60-82b1-d0c495d7f03e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
