<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The maximum Percentage of discount ()_23843f</name>
   <tag></tag>
   <elementGuidId>1b726c70-96d1-40fb-b47a-b2ab8974e3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79307c62-870c-4c37-8e3a-4e7681dbd028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>e7b0b200-5756-4e35-bddb-f35ca00ca95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>8af233f8-a3f5-4fde-a0ee-1a18d2ff83ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f3b7e37-de9c-40a1-acf2-db63bf2d92df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>d1cc2a3a-b765-4a9b-a3b1-bddbe679d19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>19c42bca-eb19-48f7-869f-3de0e919e082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>feb68962-f03d-424c-a602-8b3729476f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f09da40d-1a45-4ed1-85a0-348a37403e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input&quot;)</value>
      <webElementGuid>12514d5a-8752-430c-bf71-139a52a121d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4ad7200-1a58-4c02-982d-0a267339db19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>17cc17c5-5c36-4dbd-8bba-f3e4a4643453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input</value>
      <webElementGuid>219c2a8e-2446-49f6-8660-4f7b990672f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a29610d6-494a-4a64-9909-d8dae4b98436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>c429db2b-d9f1-4e17-8aaf-427c33574c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6f3e7168-6be3-442f-a9b0-e3e55e0535b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6bfb4473-2ecf-49c4-9d21-9ff68ab05eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c07e5e59-0331-4842-8e26-9ee728957bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input&quot;)</value>
      <webElementGuid>594fa944-8f49-4686-922f-5e2506f53969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input']</value>
      <webElementGuid>930de7c2-a310-4876-afe0-f5f05f365d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage']/input</value>
      <webElementGuid>17bb3de1-2706-48c5-90a5-2103aa09e070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>09adf0d1-0e1b-4981-b227-a0ce40bd34c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input' and @name = 'AccumedFacilityUserCreateForm:j_idt177:maximumDiscountPercentage_input' and @type = 'text']</value>
      <webElementGuid>a63e20ec-31c0-4ec9-91ce-d6c450c34b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
