<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_AccumedFacilityUserC_10f9ca</name>
   <tag></tag>
   <elementGuidId>8d482ebd-24e7-4c4d-a73c-bf24bed02a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85ccbe07-6b84-4bae-86eb-4f2aa82913cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm</value>
      <webElementGuid>7d27960d-01b2-4326-8156-7319564f5e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm</value>
      <webElementGuid>1200cab9-b53d-47c0-bd47-611051bb00df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fc707dd6-b482-4df1-8466-0a1c1af8ed3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-password ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>54f582b3-2b64-46da-9fdf-007c68351557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Accumed Password</value>
      <webElementGuid>a2930a7a-8fb9-4f29-b50f-cc4aee5c510f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2e065723-412c-4251-a1c9-066c622d8775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c3484ba-a406-4960-a994-5f60cc346355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbb7bfad-4310-4723-acc3-5bb7422cf3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm&quot;)</value>
      <webElementGuid>d5846523-fc00-44e5-87d1-b541bd6e4767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>901e01b6-0961-489b-ba72-cd79b262d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm</value>
      <webElementGuid>e54ce5fd-004b-49f9-8f7d-ceabb5e315a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm</value>
      <webElementGuid>022deed5-863d-4da4-91b4-ca9cf7cf3f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cc23c9b6-4ef6-4629-8297-a50cc137b73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-password ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>696606ef-c1e1-4df8-ad3a-57f2003ff2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Accumed Password</value>
      <webElementGuid>1bdebdeb-3577-48fa-8d93-05b1388e15b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>480d87bf-a66f-4825-994e-970b6718e95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccdaf287-370a-4a4c-8483-9eff1802f55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58b1652f-798a-46f4-87b7-5fd38709a09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm&quot;)</value>
      <webElementGuid>f48665a7-5f6c-47c0-9cfc-1c98a0c8961a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm']</value>
      <webElementGuid>2731c630-ad92-454d-85a9-da0305d6b2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='AccumedFacilityUserCreateForm:j_idt177:j_idt180']/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>3e09affc-3de0-4b16-ac4f-8e6cbb39e837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>005d94c4-c859-461a-bbf6-fd1ce892c931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm' and @name = 'AccumedFacilityUserCreateForm:j_idt177:accumedPasswordConfirm' and @type = 'password' and @title = 'Accumed Password']</value>
      <webElementGuid>074df139-538f-4dad-a62b-9c7e29203f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
