<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CASHIER ADMIN</name>
   <tag></tag>
   <elementGuidId>147eaa96-1855-4947-94b0-b31fe85be324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-picklist-item.ui-corner-all.ui-sortable-handle.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserCreateForm:j_idt177:pickList']/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>47398f75-e656-47c1-896d-3b035e1a5b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover</value>
      <webElementGuid>0653606d-8814-4875-888a-acb6f4c4b350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>2031</value>
      <webElementGuid>5390186a-0e55-470d-ac2d-ff54901e0cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>CASHIER ADMIN</value>
      <webElementGuid>7833cade-a7d2-4cdf-b158-c857b1e6e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>aba9b14c-ef75-43e9-a8aa-fc3c7a247614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CASHIER ADMIN</value>
      <webElementGuid>7b80ace1-579a-4716-ba1d-c68830975e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:pickList&quot;)/div[@class=&quot;ui-picklist-list-wrapper&quot;]/ul[@class=&quot;ui-widget-content ui-picklist-list ui-picklist-source ui-corner-bottom ui-sortable&quot;]/li[@class=&quot;ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover&quot;]</value>
      <webElementGuid>d2bb858d-01e8-4671-9cbb-555b1fbd4c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserCreateForm:j_idt177:pickList']/div/ul/li[4]</value>
      <webElementGuid>55ab60d5-aa9f-4fbd-bf7f-fa15aadb029f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATOR'])[1]/following::li[1]</value>
      <webElementGuid>bdb223c0-0157-48fa-9b39-45bc626cf65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTANT'])[1]/following::li[2]</value>
      <webElementGuid>1254551f-9c3b-4b63-b1b3-08168208756c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCHI_MAPPING_TOOL'])[1]/preceding::li[1]</value>
      <webElementGuid>ca88c878-5519-473c-a862-aeeabfb4fbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ggggf'])[1]/preceding::li[2]</value>
      <webElementGuid>164ea6ff-fb1e-4072-9174-26287797f756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CASHIER ADMIN']/parent::*</value>
      <webElementGuid>fd86a923-ea5e-428e-b56a-df3b4c2c4120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[4]</value>
      <webElementGuid>c9d038e6-0757-4a17-b648-6e8edbfa1a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'CASHIER ADMIN' or . = 'CASHIER ADMIN')]</value>
      <webElementGuid>dd58254b-f316-47ad-b0ff-3e995c9c2679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
