<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_COLLECTOR</name>
   <tag></tag>
   <elementGuidId>4e3379f0-f25c-4017-b9ca-0bc977825a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-picklist-item.ui-corner-all.ui-sortable-handle.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccumedFacilityUserCreateForm:j_idt177:pickList']/div/ul/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>44b50188-84c5-454b-850b-9c88e7f58c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover</value>
      <webElementGuid>630a4917-0df0-4dbf-aba7-cdac1d1213f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>2030</value>
      <webElementGuid>aca82662-3a7e-43e1-87b3-964cb8c05280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>COLLECTOR</value>
      <webElementGuid>88e18687-3cfc-4d22-9b3b-3c2db12a3334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f8d93667-140a-4a33-9988-f6fd3d38bc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLLECTOR</value>
      <webElementGuid>c6fded12-f7bb-4996-9e5f-337db64de036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccumedFacilityUserCreateForm:j_idt177:pickList&quot;)/div[@class=&quot;ui-picklist-list-wrapper&quot;]/ul[@class=&quot;ui-widget-content ui-picklist-list ui-picklist-source ui-corner-bottom ui-sortable&quot;]/li[@class=&quot;ui-picklist-item ui-corner-all ui-sortable-handle ui-state-hover&quot;]</value>
      <webElementGuid>625c819e-1f16-4436-995b-d6b82ef9cae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccumedFacilityUserCreateForm:j_idt177:pickList']/div/ul/li[7]</value>
      <webElementGuid>ceb48d32-1757-4146-9369-1031ed7bab8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCHI_MAPPING_TOOL'])[1]/following::li[1]</value>
      <webElementGuid>5f799794-4d50-4018-be91-885b02571fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHIER ADMIN'])[1]/following::li[2]</value>
      <webElementGuid>c901e927-7cb2-4504-899f-7cc6f2d73924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ggggf'])[1]/preceding::li[1]</value>
      <webElementGuid>18c87a9b-59c4-4db9-824e-4eac45276b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kareemoi'])[1]/preceding::li[2]</value>
      <webElementGuid>a538233c-4bb3-419c-8995-91414aac827d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COLLECTOR']/parent::*</value>
      <webElementGuid>640ecb39-cc79-4752-8851-835f78bad545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[7]</value>
      <webElementGuid>93ad2d18-def0-46d9-8f58-d8f29ea31ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'COLLECTOR' or . = 'COLLECTOR')]</value>
      <webElementGuid>3302475e-9f5d-4a33-b9b7-80a7d11ece76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
